In [3]:
import numpy as np

In [2]:
def selection_sort(array):
    n = array.shape[0]
    for i in range(n):
        max_i = array[i]
        swap_index = i
        for j in range(i,n):
            if(array[j]>max_i):
                max_i = array[j]
                swap_index = j
        
        temp = array[i]
        array[i] = array[swap_index]
        array[swap_index] = temp
        
    return array

In [4]:
array = np.array([2,3,5,3,6])
selection_sort(array)

array([6, 5, 3, 3, 2])

In [10]:
def insertion_sort(array):
    n = array.shape[0]
    for i in range(n):
        j_temp = i
        temp = array[i]
        for j in range(i):
            if(array[i]>array[j]):
                j_temp = j
                break
        for k in range(i,j_temp,-1):
            array[k] = array[k-1]
        array[j_temp] = temp
    return array

In [11]:
array = np.array([2,3,5,3,6])
insertion_sort(array)

array([6, 5, 3, 3, 2])

In [41]:
def merge(array1, array2):
    n1 = array1.shape[0]
    n2 = array2.shape[0]
    array = np.zeros(n1+n2, dtype = int)
    i1 = 0
    i2 = 0
    for i in range(n2+n1):
        if(i1>=n1):
            array[i] = array2[i2]
            i2+=1
        elif(i2>=n2):
            array[i] = array1[i1]
            i1+=1
        elif(array1[i1]>array2[i2]):
            array[i] = array1[i1]
            i1+=1
        else:
            array[i] = array2[i2]
            i2+=1
    return array

In [44]:
def merge_sort(array):
    n = array.shape[0]
    if n == 1:
        return array
    else:
        m = int((n-1)/2)
        return merge(merge_sort(array[0:m+1]), merge_sort(array[m+1:n]))

In [45]:
array = np.array([2,3,5,3,6])
merge_sort(array)

array([6, 5, 3, 3, 2])

In [46]:
def heapify(array, n, i):
    smallest = i
    l = 2*i+1
    r = 2*i+2
    if(l<n and array[l]<array[smallest]):
        smallest = l
    if(r<n and array[r]<array[smallest]):
        smallest = r
    if(smallest!=i):
        array[i],array[smallest] = array[smallest], array[i]
        heapify(array, n, smallest)

In [51]:
def heap_sort(array):
    n = array.shape[0]
    for i in range(n-1,-1,-1):
        heapify(array, n, i)
    for i in range(n-1, 0, -1):
        array[i], array[0] = array[0], array[i]
        heapify(array, i, 0)
    return array

In [52]:
array = np.array([2,3,5,3,6])
heap_sort(array)

array([6, 5, 3, 3, 2])